# Generated by Django 3.2.6 on 2021-08-27 12:41

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15)),
                ('owner_id', models.BigIntegerField(null=True)),
                ('engine_power', models.CharField(blank=True, max_length=15)),
                ('no_of_wheels', models.CharField(blank=True, max_length=10)),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326)),
                ('price_perhour', models.FloatField()),
                ('is_available', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tractor',
                'verbose_name_plural': 'Tractor',
            },
        ),
        migrations.CreateModel(
            name='Tractor_Types',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uud', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tractor_Sub_Types_Activities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uud', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('tractor_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tractor.tractor_types')),
            ],
        ),
        migrations.CreateModel(
            name='Tractor_Attachments',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('atach_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tractor.attachments')),
                ('tractor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tractor.tractor')),
            ],
        ),
        migrations.AddField(
            model_name='tractor',
            name='tractor_sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tractor.tractor_sub_types_activities'),
        ),
        migrations.AddField(
            model_name='tractor',
            name='tractor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tractor.tractor_types'),
        ),
    ]
