# Generated by Django 3.2.7 on 2021-09-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tractor', '0002_alter_tractor_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractor_types',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
