# Generated by Django 3.2.7 on 2021-09-06 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0008_alter_order_order_status'),
        ('tractor', '0003_alter_tractor_types_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Rating_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True)),
                ('review', models.TextField(blank=True, help_text='Not Required', verbose_name='description')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('tractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tractor.tractor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
