# Generated by Django 3.2.7 on 2021-09-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_key',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
