# Generated by Django 3.2.7 on 2021-09-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.PositiveSmallIntegerField(choices=[('Order Placed', 'Received'), ('Order Accepted', 'In Process'), ('In Transit', 'Out For Delivery'), ('Delivered', 'Delivered')], default=1),
        ),
    ]
