# Generated by Django 3.2.7 on 2021-09-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Order Accepted', 'Order Accepted'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], default='Order Placed', max_length=20),
        ),
    ]
