# Generated by Django 3.2.6 on 2021-09-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrating',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(4, 'excellent'), (3, 'very good'), (2, 'good'), (1, 'bad')]),
        ),
    ]
