# Generated by Django 3.2.6 on 2021-09-02 06:09

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_remove_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_status', models.CharField(max_length=150)),
                ('shipment_date', models.DateTimeField()),
                ('dispatch_mode', models.CharField(blank=True, max_length=150)),
                ('delivery_status', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text='Not Required', verbose_name='description')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='orders.order')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Shippment_Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326)),
                ('curr_date_time', models.DateTimeField()),
                ('description', models.TextField(blank=True, help_text='Not Required', verbose_name='description')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shipment', to='shipment.shipment')),
            ],
            options={
                'ordering': ('-curr_date_time',),
            },
        ),
    ]
