# Generated by Django 3.2.7 on 2021-10-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
